services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./host:/usr/share/nginx/html/host:ro
      - ./sub.host:/usr/share/nginx/html/sub.host:ro
