name: Pyre Analyze

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pyre:
    name: Pyre Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyre-check django

      - name: Run Pyre analyze
        working-directory: ${{ github.workspace }}/pysa
        run: |
          pyre analyze
